### ISSUE TITLE
Implement unit tests

### ISSUE THREAD

**Issue by georg-wolflein** [tomcontileslie/ThatChord#11]
Great project! I feel in the long run that unit tests would be a great way to spot bugs early that might be introduced by changes to the code. For example, when modifying the chord searching algorithm to make it more efficient, having unit tests would ensure that these changes don't break the algorithm. I'd recommend [pytest](http://pytest.org)...

**Comment by tomcontileslie** [comment]
Thank you Georg! I've had a look at pytest and have set up integration with Travis CI. Testing files are being developed in the `testing` branch.

**Comment by tomcontileslie** [comment]
First attempt merged and build passing!

**Comment by tomcontileslie** [comment]
First attempt merged and build passing!
