### ISSUE TITLE
SETTINGS option wont work on linux

### ISSUE THREAD

**Issue by reiniscirpons** [tomcontileslie/ThatChord#14]
When attempting to run `python3 thatchord.py SETTINGS` on Ubuntu I get the following error
```
sh: 1: open: not found
```
Apparently there is no `open` command in linux. According to [this answer](https://stackoverflow.com/questions/434597/open-document-with-default-os-application-in-python-both-in-windows-and-mac-os/435631#435631) on stack exchange using `xdg-open` should do the trick.

**Comment by tomcontileslie** [comment]
This is fixed by #15 and merged. Thanks for raising!
