### ISSUE TITLE
Chords on guitar are slow

### ISSUE THREAD

**Issue by tomcontileslie** [tomcontileslie/ThatChord#8]
Chords with 5 or more notes can take a few seconds to run on instruments like guitar, due to the large number of possibilities for valid frets on each string. How can we improve this? I can see no immediate improvements to the general formula that ThatChord uses:

- check valid frets on each string
- look at all combinations of valid frets and remember one combination if it plays the full chord rather than a subset of its notes
- rank valid combinations

but perhaps some combinations can be disregarded earlier (spread of fingers is higher than some high cutoff e.g. 8) to reduce the number of combinations recalled.

**Comment by reiniscirpons** [comment]
I think wed get good improvement if we refined the chord selection process, and generated chords which have all of the required notes directly, instead of generating all and then checking which have a full subset.
For example, in the current model if we had a chord which needed 6 different notes then we have around 12 choices of fret on each string giving about `12^6=3*10^6` total chords. However once we select the note on the first string we only have 5 notes remaining etc. so we effectively only have approximately `12*10*8*6*4*2=5*10^4` chords which have all the required notes, about 60 times less.

**Comment by tomcontileslie** [comment]
I think this is a good idea - though the approach has to be a bit more subtle, since sometimes the instrument has more strings than there are notes in the chord. For example, C major contains only the notes C, E, G - to play those three notes on guitar, some of these notes will appear several times on different strings. So if we have selected a fret on the first string which gives a C, this does not discount the possibility that C may appear on a later string.

I'm not sure what the best way of getting around that is, because I do agree that there is a lot of unnecessary computation in considering configurations which do not play the full subset. And there certainly are cases where the requested chord has 6 notes, and the instrument has 6 strings, in which case your 60x factor does hold. So maybe it's a question of checking, after having selected notes for the first n strings, whether the number of notes not yet played is equal to the number of remaining strings - at which point we can begin discounting possibilities. I'm not sure how much of a speedup we get, though, since re-computing that also takes time. I think that this is worth implementing, though - although care will have to be taken around the `important` setting, which is a bit of a wild card, since it can claim that even if a chord request has 4 notes, a subset of those notes of size `important` will suffice for a configuration to be valid.

For now, I'm working on a different approach that tackles a separate part of the slowdown: currently, all `10^6` options are stored in a list then sorted by rank at the end. But looking at how input is taken: as soon as the request is given, we know exactly how many of those options we need to see: if someone asks for the 10th best option, we need only ever see the 10 best configurations found so far. We shouldn't have to store a list of length more than 10 in that case. This will be an improvement in memory more than time perhaps, but does not overlap at all with the speedup you're suggesting :)

**Comment by tomcontileslie** [comment]
I haven't uploaded yet because the modification in the workflow has broken loads of tests - but I have a working version of the "store few options" solution which has resulted in practically no speedup whatsoever. I'll get started on clever skipping soon, which should help a little more :)

**Comment by tomcontileslie** [comment]
Store few options and clever skipping have both been implemented in PR #16. This doesn't skip everything, but still reduces 6-note guitar chords from 7s to 1s on my computer. I'm going to consider this satisfactory progress for now and close the issue. More issues relating to speed and/or optimisation PRs remain welcome.
