### ISSUE TITLE
Fully configurable command line interface

### ISSUE THREAD

**Issue by joshwd36** [tomcontileslie/ThatChord#9]
It would be useful to have command line options that can specify the settings listed in settings.py, to allow the user to avoid having to modify that file. Perhaps something similar to the form:
```
python thatchord.py <chord> [OPTIONS]
Options:
-i, --instrument: instrument preset
-r, --ranking: ranking preset
-o, --output: print, splash, or none
-s, --save: single, library, or none
-d, --directory: diagrams directory
```
There could also potentially be options for defining custom instruments, perhaps allowing the user to specify a file which contains instrument definitions.

**Comment by tomcontileslie** [comment]
This is exactly the kind of thing I didn't have enough perspective to think of! Thank you for raising this Josh!

**Comment by tomcontileslie** [comment]
Two changes:
- v2.0.0 introduces `settings.yml` which is easier to edit, involving less scrolling through seas of comments.
- Commit a46c43c adds CLI functionality if the input type is set to `TERMINAL`. You can override the settings file's values with your choice of instrument and ranking presets, as well as output options. You can also specify the location of a different YML settings file to load the settings from. The custom YML file's values are overriden by the CLI-entered values of instrument presets etc. if both happen to be specified.

**Comment by tomcontileslie** [comment]
How well does this tackle #9, @joshwd36?

**Comment by joshwd36** [comment]
> 
> 
> How well does this tackle #9, @joshwd36?

That looks really good!
